package com.ramsai.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0d631b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF2e7d32)
val md_theme_light_onPrimaryContainer = Color(0xFFcbffc2)
val md_theme_light_secondary = Color(0xFF964900)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFfc820c)
val md_theme_light_onSecondaryContainer = Color(0xFF5e2c00)
val md_theme_light_tertiary = Color(0xFF7b4b00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF9d6000)
val md_theme_light_onTertiaryContainer = Color(0xFFffefe1)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFf8faf8)
val md_theme_light_onBackground = Color(0xFF191c1b)
val md_theme_light_surface = Color(0xFFf8faf8)
val md_theme_light_onSurface = Color(0xFF191c1b)
val md_theme_light_surfaceVariant = Color(0xFFe1e3e1)
val md_theme_light_onSurfaceVariant = Color(0xFF40493d)
val md_theme_light_outline = Color(0xFF707a6c)
val md_theme_light_inverseOnSurface = Color(0xFFeff1ef)
val md_theme_light_inverseSurface = Color(0xFF2e3130)
val md_theme_light_inversePrimary = Color(0xFF88d982)

// custom colors based on HTML definition
val surface_container_lowest = Color(0xFFffffff)
val surface_container_low = Color(0xFFf2f4f2)
val surface_container = Color(0xFFeceeec)
val surface_container_high = Color(0xFFe6e9e7)
val surface_container_highest = Color(0xFFe1e3e1)
val primary_fixed = Color(0xFFa3f69c)
val on_primary_fixed = Color(0xFF002204)
val secondary_fixed_dim = Color(0xFFffb786)
val on_secondary_fixed_variant = Color(0xFF723600)
